import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CANDY GO!GO! ツアー情報</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>CANDY GO!GO!BRAVE VENUS TOUR 2021</h1>
        <div className={styles.wrapper}>
          <div className={styles.box1}>
        <ul >
          <li>10月9日: 仙台  仙台MACANA</li>
          <li>10月30日: 大阪  心斎橋VARON</li>
          <li>11月4日: 名古屋  HOLIDAY NEXT NAGOYA</li>
          <li>11月21日: 新潟  新潟 GOLDEN PIGS</li>
          <li>12月6日: 東京  TSUTAYA O-EAST</li>
        </ul>
        </div>
        <div className={styles.box2}>
          <Image src="/tour-map.jpg" alt="map" width="400" height="400" />
        </div>
        </div>
      </main>

      <footer className={styles.footer}>
        created by sassy
      </footer>
    </div>
  )
}
