import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CANDY GO!GO! ツアー情報</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <div>
        CANDY GO!GO!BRAVE VENUS TOUR 2021
        </div>
        <nav>
          <ul className={styles.nav_item_wrapper}>
            <li className={styles.nav_item}><a href="#sendai">仙台</a></li>
            <li className={styles.nav_item}><a href="#ohsaka">大阪</a></li>
            <li className={styles.nav_item}><a href="#nagoya">名古屋</a></li>
            <li className={styles.nav_item}><a href="#nigata">新潟</a></li>
            <li className={styles.nav_item}><a href="#tokyo">東京</a></li>
          </ul>
        </nav>
      </header>

      <main className={styles.main}>
        <h1>CANDY GO!GO!BRAVE VENUS TOUR 2021</h1>
        <div className={styles.wrapper}>
          <div className={styles.box1}>
            <ul >
              <li><span>10月9日(土):</span><span> 仙台</span><span> 仙台MACANA</span></li>
              <li><span>10月30日(土):</span><span> 大阪 </span><span> 心斎橋VARON</span></li>
              <li><span>11月14日(日):</span><span> 名古屋</span><span> HOLIDAY NEXT NAGOYA</span></li>
              <li><span>11月21日(日):</span><span> 新潟</span><span> 新潟 GOLDEN PIGS</span></li>
              <li><span>12月6日(月):</span><span> 東京</span><span> TSUTAYA O-EAST</span></li>
            </ul>
          </div>
          <div className={styles.box2}>
            <Image src="/tour-map.jpg" alt="map" width="400" height="400" />
          </div>
        </div>
        <div className={styles.place_item}>
          <a id="sendai"></a>
          <h2>仙台<span className={styles.end}>終了</span></h2>
          <div>
          2021年10月9日（土）<br />
仙台MACANA<br />
<button><a href="https://goo.gl/maps/YP8BHcshb67t2hHw5">地図</a></button><br />
OPEN15:00（前物販・・チェキ、CD・DVD、Tシャツなどの販売あり）<br />
START15:30　<br />
＊約2時間公演予定<br />
終演後物販　17:40～19:00<br />
<br />
料金：予約＆前売2500円　当日3000円　各１D代別<br />

          </div>
        </div>
        <div className={styles.place_item}>
          <a id="ohsaka"></a>
          <h2>大阪</h2>
          <div>
          2021年10月30日（土）<br />
心斎橋VARON<br />
<button><a href="https://goo.gl/maps/zMAbDeaDWEsypdBG7">地図</a></button><br />
OPEN15:00<br />
START15:30　<br />
＊約2時間公演予定 <br />
終演後物販　17:40～19:00<br />
<br />
料金：予約＆前売2500円　当日3000円　各１D代別<br />
<br />
予約受付中<br />
<button><a href="https://candygogo.jp/ticket/">予約フォーム</a></button>
          </div>
        </div>
        <div className={styles.place_item}>
          <a id="nagoya"></a>
          <h2>名古屋</h2>
          <div>
          2021年11月14日（日）<br />
HOLIDAY NEXT NAGOYA<br />
<button><a href="https://goo.gl/maps/H2BetYd5vgDjeYkG7">地図</a></button><br />
OPEN15:00<br />
START15:30　<br />
<br />
料金：予約＆前売2500円　当日3000円　各１D代別<br />
予約受付中<br />
<button><a href="https://candygogo.jp/ticket/">予約フォーム</a></button>
          </div>
        </div>
        <div className={styles.place_item}>
          <a id="nigata"></a>
          <h2>新潟</h2>
          <div>
          2021年11月21日（日）<br />
          新潟GOLDEN PIGS　<br />
          <button><a href="https://goo.gl/maps/MJcH81enUm48YxPY7">地図</a></button><br />
          OPEN15:00<br />
          START15:30　<br />
          <br />
          料金：予約＆前売2500円　当日3000円　各１D代別<br />
          予約受付中<br />
          <button><a href="https://candygogo.jp/ticket/">予約フォーム</a></button>
          </div>
        </div>
        <div className={styles.place_item}>
          <a id="tokyo"></a>
          <h2>東京</h2>
          <div>
          12月6日（月） <br />
          TSUTAYA O-EAST（東京・渋谷） <br />
          <button><a href="https://goo.gl/maps/D4MuCsDjuZHSxXdLA">地図</a></button><br />
OPEN17:00<br />
START17:55　 <br />
<br />
予約2500円　当日3000円　１D代別 <br />
予約受付中<br />
<button><a href="https://candygogo.jp/ticket/">予約フォーム</a></button>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        created by sassy
      </footer>
    </div>
  )
}
